  version: 2.1
  orbs:
    terraform: circleci/terraform@3.0.0
  jobs:
    single-job-lifecycle:
      executor: terraform/default
      working_directory: "~/src"
      steps:
        - checkout
        - terraform/init:
            path: "./1-IAC-Terraform"
        - terraform/validate:
            path: "./1-IAC-Terraform"
        - terraform/fmt:
            path: "."
        - terraform/plan:
            path: "./1-IAC-Terraform"
            var: "deploy-name=almanza-cluster,env=dev,access_key=$aws_access_key_id,secret_key=aws_secret_access_key"
  workflows:
    single-job-lifecycle:
      jobs:
        - single-job-lifecycle:
            context:
              - terraform