version: 2.1
orbs:
  terraform: "circleci/terraform@dev:alpha"
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          workspace-root: ./1-IAC-Terraform
      - terraform/validate:
          checkout: true
          context: terraform
          workspace-root: ./1-IAC-Terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          workspace-root: ./1-IAC-Terraform
          requires:
            - terraform/validate

