version: 2.1
orbs:
  terraform: "circleci/terraform@1.1.0"
workflows:
  deploy_infrastructure:
    jobs: 
      - terraform/fmt:
          path: 1-IAC-Terraform
          checkout: true
          context: terraform
      - terraform/validate:
          path: 1-IAC-Terraform
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: 1-IAC-Terraform
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate

