  version: 2.1
  orbs:
    terraform: circleci/terraform@3.0.0
  jobs:
    single-job-lifecycle:
      executor: terraform/default
      working_directory: "./-IAC-Terraform"
      steps:
        - checkout
        - terraform/init:
            path: "."
        - terraform/validate:
            path: "."
        - terraform/fmt:
            path: "."
        - terraform/plan:
            path: "."
        - terraform/apply:
            path: "."
        - terraform/destroy:
            path: "."
  workflows:
    single-job-lifecycle:
      jobs:
        - single-job-lifecycle